### ISSUE TITLE
Energy

### ISSUE THREAD

**Issue by elektro-freak** [steff393/wbec#56]
Hallo, 

aus irgendeinem Grund hat sich die Gesamtladeleistung am 31.12. umm 11:00 wieder aus einen alten Wert zurückgesetzt.

MQTT: wbec/lp/1/energy (eigentlich 3601 zurück auf 2588)

Dies verfälscht nun mein kompletten Monitoring/Reporting.
Ist dies der Wert seit installation oder seit letztem Stromausfall? Kannst sich einer das Problem erklären bzw. beheben ?

Danke
Gruß

**Comment by steff393** [comment]
Hallo @elektro-freak,
ich kann leider nur die Werte ausgeben, die die Heidelberg über den Modbus schickt. wbec merkt sich diese Werte nicht lokal.
Der Wert der in wbec/lp/1/energy übertragen wird ist der Wert "Energy since Installation", Register 17+18
![grafik](https://user-images.githubusercontent.com/73853447/212980662-35e2aeda-b465-4bfa-ba94-7372d0e8205c.png)
